version: '3'

services:
  logstash0: 
    build: ./node0/
    container_name: "logstash0"
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - samplerestmongo_logs:/logs
    networks:
      - elk_net 
      - elasticcluster_esnet
volumes:
  samplerestmongo_logs:
    external: true
# Network configuration
networks: 
  elk_net:
  elasticcluster_esnet:
    external: true