version: '2'

services:
  logstash0: 
    # build: ./node0/
    image: docker.elastic.co/beats/filebeat:5.6.4
    container_name: "logstash0"
    ports:
      - "5044:5044"
  filebeat:
    build: ./filebeat
    container_name: "filebeat"
    # volumes:
    #   - type: "bind"
    #     source: /filebeat/filebeat.yml
    #     target: /usr/share/filebeat/filebeat.yml