version: '2'

services:
# Logstash Container
  logstash0: 
    build: ./logstash-cluster/node0
    container_name: logstash0
    ports:
      - 5044:5044
      - 9600:9600
    networks:
      - elk_net 
# Elasticsearch Container
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=docker-elastic-cluster
      - node.name=es-node-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk_net
  elasticsearch2:
    build: ./elasticsearch
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-elastic-cluster
      - node.name=es-node-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - elk_net
# Kibana Container Configuration
  kibana:
    build: ./kibana
    container_name: kibana
    # volumes:
    #   - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    # environment: 
    #   ELASTICSEARCH_URL: elasticsearch
    networks:
      - elk_net
    ports:
      - 5601:5601
volumes:
  esdata1:
  esdata2:
# Network configuration
networks: 
  elk_net: