version: '2'

services:
# Filebeat container
  filebeat:
    build: ./filebeat
    container_name: filebeat
    volumes:
      - samplerestmongo_springboot_logs:/logs
    networks:
      - elk_net
# Logstash Container
  logstash0: 
    build: ./logstash-cluster/node0
    container_name: "logstash0"
    ports:
      - "5044:5044"
    # volumes:
    #   - samplerestmongo_springboot_logs:/logs
    networks:
      - elk_net 
# Elasticsearch Container
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
    networks: 
      - elk_net

volumes:
  samplerestmongo_springboot_logs:
    external: true
# Network configuration
networks: 
  elk_net: