version: '2'

services:
# Filebeat container
  # filebeat:
  #   build: ./filebeat
  #   container_name: filebeat
  #   volumes:
  #     - samplerestmongo_springboot_logs:/logs
  #   ports:
  #     - 5045
  #   networks:
  #     - elk_net
# Logstash Container
  logstash0: 
    build: ./logstash-cluster/node0
    container_name: logstash0
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - samplerestmongo_logs:/logs
    networks:
      - elk_net 
# Elasticsearch Container
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: elasticsearch
    restart: always
    environment:
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:ParallelGCThreads=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - elk_net
# Kibana Container Configuration
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
    container_name: kibana
    # volumes:
    #   - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk_net
    ports:
      - 5601:5601
volumes:
  samplerestmongo_logs:
    external: true
  esdata:
# Network configuration
networks: 
  elk_net: